### PR TITLE
Master

### PR DESCRIPTION
**Pull request by hendrik-weiler**

### CODE REVIEW

**Comment by hendrik-weiler** [comment]
Ive refactored it and added aswell screen location for top left coordinates and width and height of the sprite.

**Comment by hendrik-weiler** [comment]
Well all tests are passing, but now when you try to change map you get this error and i dont know why:
```
[error] Exception in thread "Thread-13" java.lang.InterruptedException
[error] 	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1301)
[error] 	at scala.concurrent.impl.Promise$DefaultPromise.tryAwait(Promise.scala:202)
[error] 	at scala.concurrent.impl.Promise$DefaultPromise.ready(Promise.scala:218)
[error] 	at scala.concurrent.impl.Promise$DefaultPromise.result(Promise.scala:223)
[error] 	at scala.concurrent.Await$$anonfun$result$1.apply(package.scala:116)
[error] 	at scala.concurrent.BlockContext$DefaultBlockContext$.blockOn(BlockContext.scala:53)
[error] 	at scala.concurrent.Await$.result(package.scala:116)
[error] 	at rpgboss.lib.GdxUtils$.syncRun(GdxUtils.scala:24)
[error] 	at rpgboss.player.ScriptThread$$anon$2$$anonfun$run$1.apply(ScriptThread.scala:78)
[error] 	at rpgboss.player.ScriptThread$$anon$2$$anonfun$run$1.apply(ScriptThread.scala:77)
[error] 	at scala.Option.map(Option.scala:146)
[error] 	at rpgboss.player.ScriptThread$$anon$2.run(ScriptThread.scala:77)
[error] 	at java.lang.Thread.run(Thread.java:744)
[error] Thread death
```

**Comment by hendrik-weiler** [comment]
Well the tests passed before updating libgdx to 1.5.5

**Comment by tommycli** [comment]
Okay just undo the update to 1.5.5 then. Once the tests pass you can merge.

**Comment by hendrik-weiler** [comment]
Okay. With 1.5.5 on osx, you dont get graphic card errors anymore. The libgdx stuff is in the right place but does not display correctly.

So updating it sooner or later would be better.

**Pull request merged**
