### PR TITLE
ingame translation feature

### PR DESCRIPTION
**Pull request by hendrik-weiler**

### CODE REVIEW

**Comment by tommycli** [comment]
Pretty close to complete.

I think it should be a Map[String, String] instead of a Array[String] though.

**Comment by tommycli** [comment]
This patch was based on yours: https://github.com/rpgboss/rpgboss/commit/e27a304342ab8816f10ac35ef7a0ae7a4030cc09

It implements it using a Map[String, String].

I didn't update the all the scripts to use the new translation table though. Only the New Game, Load Game, Quit dialog, to test this.

**Comment by tommycli** [comment]
Forgot to add some files. Also needs this: https://github.com/rpgboss/rpgboss/commit/64100d435ab6fe1c32d691da9ee35dec9383fe8c

**Comment by hendrik-weiler** [comment]
With cb3933f
ive added all the remaining needed translations

**Pull request merged**
